In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("data/games-features.csv")
df

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,...,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,...,,,English French German Italian Spanish Simplifi...,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
3,40,40,Deathmatch Classic,Deathmatch Classic,Jun 1 2001,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
4,50,50,Half-Life: Opposing Force,Half-Life: Opposing Force,Nov 1 1999,0,0,1,0,0,...,,,English French German Korean,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13352,567660,567660,Baseball Riot,Baseball Riot,Jan 17 2017,0,0,1,0,0,...,Copyright (c) 2016 10tons Ltd.,,English**languages with full audio support,http://www.10tons.com/Game/baseball_riot.html,Minimum:OS: Windows XP / Vista / 7 / 8 / 10Pro...,,,,,
13353,567860,567860,Passage 4,Passage 4,Dec 13 2016,0,0,1,0,0,...,2016 copyright by netmin e.K.,,English* French Italian German* Spanish Dutch*...,http://www.libredia.com,Minimum:OS: Windows 2000/XP/Vista/7/8/10Proces...,,,,,
13354,567940,567940,Piximalism,Piximalism,Sep 26 2019,0,0,1,0,0,...,,,English,NaN,Minimum:OS: Microsoft(r) Windows(r) XP / Vista...,Recommended:OS: Microsoft(r) Windows(r) XP / V...,,,,
13355,568150,568150,Technoball,Technoball,Dec 12 2016,0,0,1,0,0,...,,,English**languages with full audio support,NaN,Minimum:OS: Windows 7 (64-bit)Processor: 2.5 G...,,,,,
13356,559250,559250,Ghostlight Manor,Ghostlight Manor,Dec 12 2016,0,0,1,0,0,...,,The real draw here is the gameplay Digital Fut...,English**languages with full audio support,http://digitalfuturelab.com/ghostlight/,Minimum:OS: Windows 7 64 bitProcessor: Intel C...,,,,Minimum:OS: Mac OSX 10.10+ 64 bitProcessor: In...,

In [4]:
df.head()

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,...,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,...,,,English French German Italian Spanish Simplifi...,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
3,40,40,Deathmatch Classic,Deathmatch Classic,Jun 1 2001,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
4,50,50,Half-Life: Opposing Force,Half-Life: Opposing Force,Nov 1 1999,0,0,1,0,0,...,,,English French German Korean,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,

In [5]:
df.columns

Index(['QueryID', 'ResponseID', 'QueryName', 'ResponseName', 'ReleaseDate',
       'RequiredAge', 'DemoCount', 'DeveloperCount', 'DLCCount', 'Metacritic',
       'MovieCount', 'PackageCount', 'RecommendationCount', 'PublisherCount',
       'ScreenshotCount', 'SteamSpyOwners', 'SteamSpyOwnersVariance',
       'SteamSpyPlayersEstimate', 'SteamSpyPlayersVariance',
       'AchievementCount', 'AchievementHighlightedCount', 'ControllerSupport',
       'IsFree', 'FreeVerAvail', 'PurchaseAvail', 'SubscriptionAvail',
       'PlatformWindows', 'PlatformLinux', 'PlatformMac', 'PCReqsHaveMin',
       'PCReqsHaveRec', 'LinuxReqsHaveMin', 'LinuxReqsHaveRec',
       'MacReqsHaveMin', 'MacReqsHaveRec', 'CategorySinglePlayer',
       'CategoryMultiplayer', 'CategoryCoop', 'CategoryMMO',
       'CategoryInAppPurchase', 'CategoryIncludeSrcSDK',
       'CategoryIncludeLevelEditor', 'CategoryVRSupport', 'GenreIsNonGame',
       'GenreIsIndie', 'GenreIsAction', 'GenreIsAdventure', 'GenreIsCasual',
       'GenreIsStrategy', 'GenreIsRPG', 'GenreIsSimulation',
       'GenreIsEarlyAccess', 'GenreIsFreeToPlay', 'GenreIsSports',
       'GenreIsRacing', 'GenreIsMassivelyMultiplayer', 'PriceCurrency',
       'PriceInitial', 'PriceFinal', 'SupportEmail', 'SupportURL', 'AboutText',
       'Background', 'ShortDescrip', 'DetailedDescrip', 'DRMNotice',
       'ExtUserAcctNotice', 'HeaderImage', 'LegalNotice', 'Reviews',
       'SupportedLanguages', 'Website', 'PCMinReqsText', 'PCRecReqsText',
       'LinuxMinReqsText', 'LinuxRecReqsText', 'MacMinReqsText',
       'MacRecReqsText'],
      dtype='str')

In [6]:
df.isnull().sum()

QueryID             0
ResponseID          0
QueryName           1
ResponseName        0
ReleaseDate         0
                   ..
PCRecReqsText       0
LinuxMinReqsText    0
LinuxRecReqsText    0
MacMinReqsText      0
MacRecReqsText      0
Length: 78, dtype: int64

In [9]:
df.dropna

<bound method DataFrame.dropna of        QueryID  ResponseID                  QueryName  \
0           10          10             Counter-Strike
1           20          20      Team Fortress Classic
2           30          30              Day of Defeat
3           40          40         Deathmatch Classic
4           50          50  Half-Life: Opposing Force
...        ...         ...                        ...
13352   567660      567660              Baseball Riot
13353   567860      567860                  Passage 4
13354   567940      567940                 Piximalism
13355   568150      568150                 Technoball
13356   559250      559250           Ghostlight Manor

                    ResponseName  ReleaseDate  RequiredAge  DemoCount  \
0                 Counter-Strike   Nov 1 2000            0          0
1          Team Fortress Classic   Apr 1 1999            0          0
2                  Day of Defeat   May 1 2003            0          0
3             Deathmatch Classic   Jun 1 2001            0          0
4      Half-Life: Opposing Force   Nov 1 1999            0          0
...                          ...          ...          ...        ...
13352              Baseball Riot  Jan 17 2017            0          0
13353                  Passage 4  Dec 13 2016            0          0
13354                 Piximalism  Sep 26 2019            0          0
13355                 Technoball  Dec 12 2016            0          0
13356           Ghostlight Manor  Dec 12 2016            0          0

       DeveloperCount  DLCCount  Metacritic  ...  \
0                   1         0          88  ...
1                   1         0           0  ...
2                   1         0          79  ...
3                   1         0           0  ...
4                   1         0           0  ...
...               ...       ...         ...  ...
13352               1         0           0  ...
13353               1         0           0  ...
13354               1         0           0  ...
13355               1         0           0  ...
13356               1         0           0  ...

                          LegalNotice  \
0
1
2
3
4
...                               ...
13352  Copyright (c) 2016 10tons Ltd.
13353   2016 copyright by netmin e.K.
13354
13355
13356

                                                 Reviews  \
0
1
2
3
4
...                                                  ...
13352
13353
13354
13355
13356  The real draw here is the gameplay Digital Fut...

                                      SupportedLanguages  \
0      English French German Italian Spanish Simplifi...
1                  English French German Italian Spanish
2                  English French German Italian Spanish
3                  English French German Italian Spanish
4                           English French German Korean
...                                                  ...
13352         English**languages with full audio support
13353  English* French Italian German* Spanish Dutch*...
13354                                            English
13355         English**languages with full audio support
13356         English**languages with full audio support

                                             Website  \
0                                                NaN
1                                                NaN
2                        http://www.dayofdefeat.com/
3                                                NaN
4                                                NaN
...                                              ...
13352  http://www.10tons.com/Game/baseball_riot.html
13353                        http://www.libredia.com
13354                                            NaN
13355                                            NaN
13356        http://digitalfuturelab.com/ghostlight/

                                           PCMinReqsText  \
0      Minimum: 500 mhz processor 96mb ram 16mb video...
1      Minimum: 500 mhz processor 96mb ram 16mb video...
2      Minimum: 500 mhz processor 96mb ram 16mb video...
3      Minimum: 500 mhz processor 96mb ram 16mb video...
4      Minimum: 500 mhz processor 96mb ram 16mb video...
...                                                  ...
13352  Minimum:OS: Windows XP / Vista / 7 / 8 / 10Pro...
13353  Minimum:OS: Windows 2000/XP/Vista/7/8/10Proces...
13354  Minimum:OS: Microsoft(r) Windows(r) XP / Vista...
13355  Minimum:OS: Windows 7 (64-bit)Processor: 2.5 G...
13356  Minimum:OS: Windows 7 64 bitProcessor: Intel C...

                                           PCRecReqsText  \
0
1
2
3
4
...                                                  ...
13352
13353
13354  Recommended:OS: Microsoft(r) Windows(r) XP / V...
13355
13356

                                        LinuxMinReqsText  LinuxRecReqsText  \
0      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
1      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
2      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
3      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
4      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
...                                                  ...               ...
13352
13353
13354
13355
13356

                                          MacMinReqsText  MacRecReqsText
0      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
1      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
2      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
3      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
4      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
...                                                  ...             ...
13352
13353
13354
13355
13356  Minimum:OS: Mac OSX 10.10+ 64 bitProcessor: In...

[13357 rows x 78 columns]>

In [10]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of        QueryID  ResponseID                  QueryName  \
0           10          10             Counter-Strike
1           20          20      Team Fortress Classic
2           30          30              Day of Defeat
3           40          40         Deathmatch Classic
4           50          50  Half-Life: Opposing Force
...        ...         ...                        ...
13352   567660      567660              Baseball Riot
13353   567860      567860                  Passage 4
13354   567940      567940                 Piximalism
13355   568150      568150                 Technoball
13356   559250      559250           Ghostlight Manor

                    ResponseName  ReleaseDate  RequiredAge  DemoCount  \
0                 Counter-Strike   Nov 1 2000            0          0
1          Team Fortress Classic   Apr 1 1999            0          0
2                  Day of Defeat   May 1 2003            0          0
3             Deathmatch Classic   Jun 1 2001            0          0
4      Half-Life: Opposing Force   Nov 1 1999            0          0
...                          ...          ...          ...        ...
13352              Baseball Riot  Jan 17 2017            0          0
13353                  Passage 4  Dec 13 2016            0          0
13354                 Piximalism  Sep 26 2019            0          0
13355                 Technoball  Dec 12 2016            0          0
13356           Ghostlight Manor  Dec 12 2016            0          0

       DeveloperCount  DLCCount  Metacritic  ...  \
0                   1         0          88  ...
1                   1         0           0  ...
2                   1         0          79  ...
3                   1         0           0  ...
4                   1         0           0  ...
...               ...       ...         ...  ...
13352               1         0           0  ...
13353               1         0           0  ...
13354               1         0           0  ...
13355               1         0           0  ...
13356               1         0           0  ...

                          LegalNotice  \
0
1
2
3
4
...                               ...
13352  Copyright (c) 2016 10tons Ltd.
13353   2016 copyright by netmin e.K.
13354
13355
13356

                                                 Reviews  \
0
1
2
3
4
...                                                  ...
13352
13353
13354
13355
13356  The real draw here is the gameplay Digital Fut...

                                      SupportedLanguages  \
0      English French German Italian Spanish Simplifi...
1                  English French German Italian Spanish
2                  English French German Italian Spanish
3                  English French German Italian Spanish
4                           English French German Korean
...                                                  ...
13352         English**languages with full audio support
13353  English* French Italian German* Spanish Dutch*...
13354                                            English
13355         English**languages with full audio support
13356         English**languages with full audio support

                                             Website  \
0                                                NaN
1                                                NaN
2                        http://www.dayofdefeat.com/
3                                                NaN
4                                                NaN
...                                              ...
13352  http://www.10tons.com/Game/baseball_riot.html
13353                        http://www.libredia.com
13354                                            NaN
13355                                            NaN
13356        http://digitalfuturelab.com/ghostlight/

                                           PCMinReqsText  \
0      Minimum: 500 mhz processor 96mb ram 16mb video...
1      Minimum: 500 mhz processor 96mb ram 16mb video...
2      Minimum: 500 mhz processor 96mb ram 16mb video...
3      Minimum: 500 mhz processor 96mb ram 16mb video...
4      Minimum: 500 mhz processor 96mb ram 16mb video...
...                                                  ...
13352  Minimum:OS: Windows XP / Vista / 7 / 8 / 10Pro...
13353  Minimum:OS: Windows 2000/XP/Vista/7/8/10Proces...
13354  Minimum:OS: Microsoft(r) Windows(r) XP / Vista...
13355  Minimum:OS: Windows 7 (64-bit)Processor: 2.5 G...
13356  Minimum:OS: Windows 7 64 bitProcessor: Intel C...

                                           PCRecReqsText  \
0
1
2
3
4
...                                                  ...
13352
13353
13354  Recommended:OS: Microsoft(r) Windows(r) XP / V...
13355
13356

                                        LinuxMinReqsText  LinuxRecReqsText  \
0      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
1      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
2      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
3      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
4      Minimum: Linux Ubuntu 12.04 Dual-core from Int...
...                                                  ...               ...
13352
13353
13354
13355
13356

                                          MacMinReqsText  MacRecReqsText
0      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
1      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
2      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
3      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
4      Minimum: OS X  Snow Leopard 10.6.3 1GB RAM 4GB...
...                                                  ...             ...
13352
13353
13354
13355
13356  Minimum:OS: Mac OSX 10.10+ 64 bitProcessor: In...

[13357 rows x 78 columns]>

In [12]:
df.shape

(13357, 78)